# Generated by Django 5.0.2 on 2025-12-03 02:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control_escolar_desit_api', '0003_alumnos_maestros'),
    ]

    operations = [
        migrations.CreateModel(
            name='Materia',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nrc', models.CharField(max_length=20, unique=True)),
                ('nombre', models.CharField(max_length=255)),
                ('seccion', models.CharField(max_length=20)),
                ('dias', models.JSONField(blank=True, default=list)),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField()),
                ('salon', models.CharField(max_length=100)),
                ('programa_educativo', models.CharField(max_length=255)),
                ('creditos', models.PositiveSmallIntegerField()),
                ('creation', models.DateTimeField(auto_now_add=True, null=True)),
                ('update', models.DateTimeField(blank=True, null=True)),
                ('profesor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='materias', to='control_escolar_desit_api.maestros')),
            ],
        ),
    ]
